// Copyright 2021-2025 ONDEWO GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.32.0
// source: ondewo/csi/conversation.proto

package csi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Conversations_CreateS2SPipeline_FullMethodName   = "/ondewo.csi.Conversations/CreateS2sPipeline"
	Conversations_GetS2SPipeline_FullMethodName      = "/ondewo.csi.Conversations/GetS2sPipeline"
	Conversations_UpdateS2SPipeline_FullMethodName   = "/ondewo.csi.Conversations/UpdateS2sPipeline"
	Conversations_DeleteS2SPipeline_FullMethodName   = "/ondewo.csi.Conversations/DeleteS2sPipeline"
	Conversations_ListS2SPipelines_FullMethodName    = "/ondewo.csi.Conversations/ListS2sPipelines"
	Conversations_S2SStream_FullMethodName           = "/ondewo.csi.Conversations/S2sStream"
	Conversations_CheckUpstreamHealth_FullMethodName = "/ondewo.csi.Conversations/CheckUpstreamHealth"
	Conversations_GetControlStream_FullMethodName    = "/ondewo.csi.Conversations/GetControlStream"
	Conversations_SetControlStatus_FullMethodName    = "/ondewo.csi.Conversations/SetControlStatus"
)

// ConversationsClient is the client API for Conversations service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// <p>Endpoints of CSI service.</p>
type ConversationsClient interface {
	// <p>Create the S2S pipeline specified in the request message. The pipeline with the specified ID must not exist.</p>
	//
	// <p>Examples:</p>
	//
	// <pre>
	// grpcurl -plaintext -d '{
	//   "id": "pizza",
	//   "s2t_pipeline_id": "default_german",
	//   "nlu_project_id": "1f3425d2-41fd-4970-87e6-88e8e121bb49",
	//   "nlu_language_code": "de",
	//   "t2s_pipeline_id": "default_german"
	// }' localhost:50051 ondewo.csi.Conversations.CreateS2sPipeline
	// </pre>
	// <samp>{}</samp>
	CreateS2SPipeline(ctx context.Context, in *S2SPipeline, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// <p>Retrieve the S2S pipeline with the ID specified in the request message.</p>
	//
	// <p>Examples:</p>
	//
	// <pre>
	// grpcurl -plaintext -d '{"id": "pizza"}' localhost:50051 ondewo.csi.Conversations.GetS2sPipeline
	// </pre>
	// <samp>{
	//   "id": "pizza",
	//   "s2t_pipeline_id": "default_german",
	//   "nlu_project_id": "1f3425d2-41fd-4970-87e6-88e8e121bb49",
	//   "nlu_language_code": "de",
	//   "t2s_pipeline_id": "default_german"
	// }
	// </samp>
	GetS2SPipeline(ctx context.Context, in *S2SPipelineId, opts ...grpc.CallOption) (*S2SPipeline, error)
	// <p>Update the S2S pipeline specified in the request message. The pipeline must exist.</p>
	//
	// <p>Examples:</p>
	//
	// <pre>
	// grpcurl -plaintext -d '{
	//   "id": "pizza",
	//   "s2t_pipeline_id": "default_german",
	//   "nlu_project_id": "1f3425d2-41fd-4970-87e6-88e8e121bb49",
	//   "nlu_language_code": "en",
	//   "t2s_pipeline_id": "default_german"
	// }' localhost:50051 ondewo.csi.Conversations.UpdateS2sPipeline
	// </pre>
	// <samp>{}</samp>
	UpdateS2SPipeline(ctx context.Context, in *S2SPipeline, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// <p>Delete the S2S pipeline with the ID specified in the request message. The pipeline must exist.</p>
	//
	// <p>Examples:</p>
	//
	// <pre>
	// grpcurl -plaintext -d '{"id": "pizza"}' localhost:50051 ondewo.csi.Conversations.DeleteS2sPipeline
	// </pre>
	// <samp>{}</samp>
	DeleteS2SPipeline(ctx context.Context, in *S2SPipelineId, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// <p>List all S2S pipelines of the server.</p>
	//
	// <p>Examples:</p>
	//
	// <pre>
	// grpcurl -plaintext localhost:50051 ondewo.csi.Conversations.ListS2sPipelines
	// </pre>
	// <samp>{
	//   "pipelines": [
	//     {
	//       "id": "pizza",
	//       "s2t_pipeline_id": "default_german",
	//       "nlu_project_id": "1f3425d2-41fd-4970-87e6-88e8e121bb49",
	//       "nlu_language_code": "de",
	//       "t2s_pipeline_id": "default_german"
	//     }
	//   ]
	// }</samp>
	ListS2SPipelines(ctx context.Context, in *ListS2SPipelinesRequest, opts ...grpc.CallOption) (*ListS2SPipelinesResponse, error)
	// <p>Processes a natural language query in audio format in a streaming fashion and returns structured, actionable data as a result.</p>
	S2SStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[S2SStreamRequest, S2SStreamResponse], error)
	// <p>Check the health of S2T, NLU and T2S servers.</p>
	//
	// <p>Examples:</p>
	//
	// <pre>
	// grpcurl -plaintext localhost:50051 ondewo.csi.Conversations.CheckUpstreamHealth
	// </pre>
	//
	// All upstreams healthy:
	// <samp>{}</samp>
	//
	// All upstreams unhealthy:
	// <samp>{
	//   "s2t_status": {
	//     "code": 14,
	//     "message": "failed to connect to all addresses"
	//   },
	//   "nlu_status": {
	//     "code": 14,
	//     "message": "failed to connect to all addresses"
	//   },
	//   "t2s_status": {
	//     "code": 14,
	//     "message": "failed to connect to all addresses"
	//   }
	// }</samp>
	CheckUpstreamHealth(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CheckUpstreamHealthResponse, error)
	// <p>Get the control stream to control sip, t2s, s2t etc. during a conversation.</p>
	GetControlStream(ctx context.Context, in *ControlStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ControlStreamResponse], error)
	// <p>Send a message on the control stream to control sip, t2s, s2t etc. during a conversation.</p>
	SetControlStatus(ctx context.Context, in *SetControlStatusRequest, opts ...grpc.CallOption) (*SetControlStatusResponse, error)
}

type conversationsClient struct {
	cc grpc.ClientConnInterface
}

func NewConversationsClient(cc grpc.ClientConnInterface) ConversationsClient {
	return &conversationsClient{cc}
}

func (c *conversationsClient) CreateS2SPipeline(ctx context.Context, in *S2SPipeline, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Conversations_CreateS2SPipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationsClient) GetS2SPipeline(ctx context.Context, in *S2SPipelineId, opts ...grpc.CallOption) (*S2SPipeline, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(S2SPipeline)
	err := c.cc.Invoke(ctx, Conversations_GetS2SPipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationsClient) UpdateS2SPipeline(ctx context.Context, in *S2SPipeline, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Conversations_UpdateS2SPipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationsClient) DeleteS2SPipeline(ctx context.Context, in *S2SPipelineId, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Conversations_DeleteS2SPipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationsClient) ListS2SPipelines(ctx context.Context, in *ListS2SPipelinesRequest, opts ...grpc.CallOption) (*ListS2SPipelinesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListS2SPipelinesResponse)
	err := c.cc.Invoke(ctx, Conversations_ListS2SPipelines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationsClient) S2SStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[S2SStreamRequest, S2SStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Conversations_ServiceDesc.Streams[0], Conversations_S2SStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[S2SStreamRequest, S2SStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Conversations_S2SStreamClient = grpc.BidiStreamingClient[S2SStreamRequest, S2SStreamResponse]

func (c *conversationsClient) CheckUpstreamHealth(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CheckUpstreamHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckUpstreamHealthResponse)
	err := c.cc.Invoke(ctx, Conversations_CheckUpstreamHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationsClient) GetControlStream(ctx context.Context, in *ControlStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ControlStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Conversations_ServiceDesc.Streams[1], Conversations_GetControlStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ControlStreamRequest, ControlStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Conversations_GetControlStreamClient = grpc.ServerStreamingClient[ControlStreamResponse]

func (c *conversationsClient) SetControlStatus(ctx context.Context, in *SetControlStatusRequest, opts ...grpc.CallOption) (*SetControlStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetControlStatusResponse)
	err := c.cc.Invoke(ctx, Conversations_SetControlStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConversationsServer is the server API for Conversations service.
// All implementations must embed UnimplementedConversationsServer
// for forward compatibility.
//
// <p>Endpoints of CSI service.</p>
type ConversationsServer interface {
	// <p>Create the S2S pipeline specified in the request message. The pipeline with the specified ID must not exist.</p>
	//
	// <p>Examples:</p>
	//
	// <pre>
	// grpcurl -plaintext -d '{
	//   "id": "pizza",
	//   "s2t_pipeline_id": "default_german",
	//   "nlu_project_id": "1f3425d2-41fd-4970-87e6-88e8e121bb49",
	//   "nlu_language_code": "de",
	//   "t2s_pipeline_id": "default_german"
	// }' localhost:50051 ondewo.csi.Conversations.CreateS2sPipeline
	// </pre>
	// <samp>{}</samp>
	CreateS2SPipeline(context.Context, *S2SPipeline) (*emptypb.Empty, error)
	// <p>Retrieve the S2S pipeline with the ID specified in the request message.</p>
	//
	// <p>Examples:</p>
	//
	// <pre>
	// grpcurl -plaintext -d '{"id": "pizza"}' localhost:50051 ondewo.csi.Conversations.GetS2sPipeline
	// </pre>
	// <samp>{
	//   "id": "pizza",
	//   "s2t_pipeline_id": "default_german",
	//   "nlu_project_id": "1f3425d2-41fd-4970-87e6-88e8e121bb49",
	//   "nlu_language_code": "de",
	//   "t2s_pipeline_id": "default_german"
	// }
	// </samp>
	GetS2SPipeline(context.Context, *S2SPipelineId) (*S2SPipeline, error)
	// <p>Update the S2S pipeline specified in the request message. The pipeline must exist.</p>
	//
	// <p>Examples:</p>
	//
	// <pre>
	// grpcurl -plaintext -d '{
	//   "id": "pizza",
	//   "s2t_pipeline_id": "default_german",
	//   "nlu_project_id": "1f3425d2-41fd-4970-87e6-88e8e121bb49",
	//   "nlu_language_code": "en",
	//   "t2s_pipeline_id": "default_german"
	// }' localhost:50051 ondewo.csi.Conversations.UpdateS2sPipeline
	// </pre>
	// <samp>{}</samp>
	UpdateS2SPipeline(context.Context, *S2SPipeline) (*emptypb.Empty, error)
	// <p>Delete the S2S pipeline with the ID specified in the request message. The pipeline must exist.</p>
	//
	// <p>Examples:</p>
	//
	// <pre>
	// grpcurl -plaintext -d '{"id": "pizza"}' localhost:50051 ondewo.csi.Conversations.DeleteS2sPipeline
	// </pre>
	// <samp>{}</samp>
	DeleteS2SPipeline(context.Context, *S2SPipelineId) (*emptypb.Empty, error)
	// <p>List all S2S pipelines of the server.</p>
	//
	// <p>Examples:</p>
	//
	// <pre>
	// grpcurl -plaintext localhost:50051 ondewo.csi.Conversations.ListS2sPipelines
	// </pre>
	// <samp>{
	//   "pipelines": [
	//     {
	//       "id": "pizza",
	//       "s2t_pipeline_id": "default_german",
	//       "nlu_project_id": "1f3425d2-41fd-4970-87e6-88e8e121bb49",
	//       "nlu_language_code": "de",
	//       "t2s_pipeline_id": "default_german"
	//     }
	//   ]
	// }</samp>
	ListS2SPipelines(context.Context, *ListS2SPipelinesRequest) (*ListS2SPipelinesResponse, error)
	// <p>Processes a natural language query in audio format in a streaming fashion and returns structured, actionable data as a result.</p>
	S2SStream(grpc.BidiStreamingServer[S2SStreamRequest, S2SStreamResponse]) error
	// <p>Check the health of S2T, NLU and T2S servers.</p>
	//
	// <p>Examples:</p>
	//
	// <pre>
	// grpcurl -plaintext localhost:50051 ondewo.csi.Conversations.CheckUpstreamHealth
	// </pre>
	//
	// All upstreams healthy:
	// <samp>{}</samp>
	//
	// All upstreams unhealthy:
	// <samp>{
	//   "s2t_status": {
	//     "code": 14,
	//     "message": "failed to connect to all addresses"
	//   },
	//   "nlu_status": {
	//     "code": 14,
	//     "message": "failed to connect to all addresses"
	//   },
	//   "t2s_status": {
	//     "code": 14,
	//     "message": "failed to connect to all addresses"
	//   }
	// }</samp>
	CheckUpstreamHealth(context.Context, *emptypb.Empty) (*CheckUpstreamHealthResponse, error)
	// <p>Get the control stream to control sip, t2s, s2t etc. during a conversation.</p>
	GetControlStream(*ControlStreamRequest, grpc.ServerStreamingServer[ControlStreamResponse]) error
	// <p>Send a message on the control stream to control sip, t2s, s2t etc. during a conversation.</p>
	SetControlStatus(context.Context, *SetControlStatusRequest) (*SetControlStatusResponse, error)
	mustEmbedUnimplementedConversationsServer()
}

// UnimplementedConversationsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConversationsServer struct{}

func (UnimplementedConversationsServer) CreateS2SPipeline(context.Context, *S2SPipeline) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateS2SPipeline not implemented")
}
func (UnimplementedConversationsServer) GetS2SPipeline(context.Context, *S2SPipelineId) (*S2SPipeline, error) {
	return nil, status.Error(codes.Unimplemented, "method GetS2SPipeline not implemented")
}
func (UnimplementedConversationsServer) UpdateS2SPipeline(context.Context, *S2SPipeline) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateS2SPipeline not implemented")
}
func (UnimplementedConversationsServer) DeleteS2SPipeline(context.Context, *S2SPipelineId) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteS2SPipeline not implemented")
}
func (UnimplementedConversationsServer) ListS2SPipelines(context.Context, *ListS2SPipelinesRequest) (*ListS2SPipelinesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListS2SPipelines not implemented")
}
func (UnimplementedConversationsServer) S2SStream(grpc.BidiStreamingServer[S2SStreamRequest, S2SStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method S2SStream not implemented")
}
func (UnimplementedConversationsServer) CheckUpstreamHealth(context.Context, *emptypb.Empty) (*CheckUpstreamHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckUpstreamHealth not implemented")
}
func (UnimplementedConversationsServer) GetControlStream(*ControlStreamRequest, grpc.ServerStreamingServer[ControlStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method GetControlStream not implemented")
}
func (UnimplementedConversationsServer) SetControlStatus(context.Context, *SetControlStatusRequest) (*SetControlStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetControlStatus not implemented")
}
func (UnimplementedConversationsServer) mustEmbedUnimplementedConversationsServer() {}
func (UnimplementedConversationsServer) testEmbeddedByValue()                       {}

// UnsafeConversationsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConversationsServer will
// result in compilation errors.
type UnsafeConversationsServer interface {
	mustEmbedUnimplementedConversationsServer()
}

func RegisterConversationsServer(s grpc.ServiceRegistrar, srv ConversationsServer) {
	// If the following call panics, it indicates UnimplementedConversationsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Conversations_ServiceDesc, srv)
}

func _Conversations_CreateS2SPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(S2SPipeline)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationsServer).CreateS2SPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Conversations_CreateS2SPipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationsServer).CreateS2SPipeline(ctx, req.(*S2SPipeline))
	}
	return interceptor(ctx, in, info, handler)
}

func _Conversations_GetS2SPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(S2SPipelineId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationsServer).GetS2SPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Conversations_GetS2SPipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationsServer).GetS2SPipeline(ctx, req.(*S2SPipelineId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Conversations_UpdateS2SPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(S2SPipeline)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationsServer).UpdateS2SPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Conversations_UpdateS2SPipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationsServer).UpdateS2SPipeline(ctx, req.(*S2SPipeline))
	}
	return interceptor(ctx, in, info, handler)
}

func _Conversations_DeleteS2SPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(S2SPipelineId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationsServer).DeleteS2SPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Conversations_DeleteS2SPipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationsServer).DeleteS2SPipeline(ctx, req.(*S2SPipelineId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Conversations_ListS2SPipelines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListS2SPipelinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationsServer).ListS2SPipelines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Conversations_ListS2SPipelines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationsServer).ListS2SPipelines(ctx, req.(*ListS2SPipelinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Conversations_S2SStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConversationsServer).S2SStream(&grpc.GenericServerStream[S2SStreamRequest, S2SStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Conversations_S2SStreamServer = grpc.BidiStreamingServer[S2SStreamRequest, S2SStreamResponse]

func _Conversations_CheckUpstreamHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationsServer).CheckUpstreamHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Conversations_CheckUpstreamHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationsServer).CheckUpstreamHealth(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Conversations_GetControlStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ControlStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConversationsServer).GetControlStream(m, &grpc.GenericServerStream[ControlStreamRequest, ControlStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Conversations_GetControlStreamServer = grpc.ServerStreamingServer[ControlStreamResponse]

func _Conversations_SetControlStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetControlStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationsServer).SetControlStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Conversations_SetControlStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationsServer).SetControlStatus(ctx, req.(*SetControlStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Conversations_ServiceDesc is the grpc.ServiceDesc for Conversations service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Conversations_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ondewo.csi.Conversations",
	HandlerType: (*ConversationsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateS2sPipeline",
			Handler:    _Conversations_CreateS2SPipeline_Handler,
		},
		{
			MethodName: "GetS2sPipeline",
			Handler:    _Conversations_GetS2SPipeline_Handler,
		},
		{
			MethodName: "UpdateS2sPipeline",
			Handler:    _Conversations_UpdateS2SPipeline_Handler,
		},
		{
			MethodName: "DeleteS2sPipeline",
			Handler:    _Conversations_DeleteS2SPipeline_Handler,
		},
		{
			MethodName: "ListS2sPipelines",
			Handler:    _Conversations_ListS2SPipelines_Handler,
		},
		{
			MethodName: "CheckUpstreamHealth",
			Handler:    _Conversations_CheckUpstreamHealth_Handler,
		},
		{
			MethodName: "SetControlStatus",
			Handler:    _Conversations_SetControlStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "S2sStream",
			Handler:       _Conversations_S2SStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "GetControlStream",
			Handler:       _Conversations_GetControlStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ondewo/csi/conversation.proto",
}
