// Copyright 2021-2025 ONDEWO GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.32.0
// source: ondewo/csi/conversation.proto

package csi

import (
	nlu "github.com/ondewo/ondewo-csi-client-go/v5/api/ondewo/nlu"
	s2t "github.com/ondewo/ondewo-csi-client-go/v5/api/ondewo/s2t"
	t2s "github.com/ondewo/ondewo-csi-client-go/v5/api/ondewo/t2s"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Control status.
type ControlStatus int32

const (
	// Status that control stream is ok
	ControlStatus_OK ControlStatus = 0
	// Status that control stream needs to stop immediately
	ControlStatus_EMERGENCY_STOP ControlStatus = 1
	// Status that voice activity detection detected start of speech
	ControlStatus_VAD_START_OF_SPEECH ControlStatus = 2
	// Status that the caller started speaking while the bot was speaking (barge-in): playback pauses and the un-played audio remainder is buffered
	ControlStatus_BARGE_IN ControlStatus = 3
	// Status sent by the server to the client to resume playback of the buffered audio remainder after a false interruption (no committed transcription final arrived within the false interruption timeout)
	ControlStatus_RESUME_PLAYBACK ControlStatus = 4
	// Status sent by the server to the client to discard the buffered audio remainder because the interruption committed as a real turn
	ControlStatus_DISCARD_REMAINDER ControlStatus = 5
	// Status reported by the client to the server via <code>SetControlStatus</code> that playback of the buffered audio remainder has resumed
	ControlStatus_PLAYBACK_RESUMED ControlStatus = 6
	// Status reported by the client to the server via <code>SetControlStatus</code> that playback of an utterance has completed
	ControlStatus_PLAYBACK_DONE ControlStatus = 7
	// Status reported by ondewo-sip to the server via <code>SetControlStatus</code> that the phone call has ENDED and the server must reset ALL per-call state in place (persistent-listener model). It is a command, not a state: it is never pushed onto the control stream
	ControlStatus_CALL_ENDED ControlStatus = 8
)

// Enum value maps for ControlStatus.
var (
	ControlStatus_name = map[int32]string{
		0: "OK",
		1: "EMERGENCY_STOP",
		2: "VAD_START_OF_SPEECH",
		3: "BARGE_IN",
		4: "RESUME_PLAYBACK",
		5: "DISCARD_REMAINDER",
		6: "PLAYBACK_RESUMED",
		7: "PLAYBACK_DONE",
		8: "CALL_ENDED",
	}
	ControlStatus_value = map[string]int32{
		"OK":                  0,
		"EMERGENCY_STOP":      1,
		"VAD_START_OF_SPEECH": 2,
		"BARGE_IN":            3,
		"RESUME_PLAYBACK":     4,
		"DISCARD_REMAINDER":   5,
		"PLAYBACK_RESUMED":    6,
		"PLAYBACK_DONE":       7,
		"CALL_ENDED":          8,
	}
)

func (x ControlStatus) Enum() *ControlStatus {
	p := new(ControlStatus)
	*p = x
	return p
}

func (x ControlStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ondewo_csi_conversation_proto_enumTypes[0].Descriptor()
}

func (ControlStatus) Type() protoreflect.EnumType {
	return &file_ondewo_csi_conversation_proto_enumTypes[0]
}

func (x ControlStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlStatus.Descriptor instead.
func (ControlStatus) EnumDescriptor() ([]byte, []int) {
	return file_ondewo_csi_conversation_proto_rawDescGZIP(), []int{0}
}

// Control message services.
type ControlMessageServiceName int32

const (
	// Unknown control message service name
	ControlMessageServiceName_UNKNOWNNAME ControlMessageServiceName = 0
	// Speech-2-Text control message service name
	ControlMessageServiceName_ondewo_s2t ControlMessageServiceName = 1
	// Text-2-Speech control message service name
	ControlMessageServiceName_ondewo_t2s ControlMessageServiceName = 2
	// NLU control message service name
	ControlMessageServiceName_ondewo_nlu ControlMessageServiceName = 3
	// SIP control message service name
	ControlMessageServiceName_ondewo_sip ControlMessageServiceName = 4
	// VTSI control message service name
	ControlMessageServiceName_ondewo_vtsi ControlMessageServiceName = 5
	// CSI control message service name
	ControlMessageServiceName_ondewo_csi ControlMessageServiceName = 6
	// Survey control message service name
	ControlMessageServiceName_ondewo_survey ControlMessageServiceName = 7
)

// Enum value maps for ControlMessageServiceName.
var (
	ControlMessageServiceName_name = map[int32]string{
		0: "UNKNOWNNAME",
		1: "ondewo_s2t",
		2: "ondewo_t2s",
		3: "ondewo_nlu",
		4: "ondewo_sip",
		5: "ondewo_vtsi",
		6: "ondewo_csi",
		7: "ondewo_survey",
	}
	ControlMessageServiceName_value = map[string]int32{
		"UNKNOWNNAME":   0,
		"ondewo_s2t":    1,
		"ondewo_t2s":    2,
		"ondewo_nlu":    3,
		"ondewo_sip":    4,
		"ondewo_vtsi":   5,
		"ondewo_csi":    6,
		"ondewo_survey": 7,
	}
)

func (x ControlMessageServiceName) Enum() *ControlMessageServiceName {
	p := new(ControlMessageServiceName)
	*p = x
	return p
}

func (x ControlMessageServiceName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlMessageServiceName) Descriptor() protoreflect.EnumDescriptor {
	return file_ondewo_csi_conversation_proto_enumTypes[1].Descriptor()
}

func (ControlMessageServiceName) Type() protoreflect.EnumType {
	return &file_ondewo_csi_conversation_proto_enumTypes[1]
}

func (x ControlMessageServiceName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlMessageServiceName.Descriptor instead.
func (ControlMessageServiceName) EnumDescriptor() ([]byte, []int) {
	return file_ondewo_csi_conversation_proto_rawDescGZIP(), []int{1}
}

// Control message methods to control services during a conversation.
type ControlMessageServiceMethod int32

const (
	// Unknown method (default)
	ControlMessageServiceMethod_UNKNOWNMETHOD ControlMessageServiceMethod = 0
	// CSI: update configuration
	//
	// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
	// <pre><code>
	//{
	//    &quot;service&quot;: &quot;ondewo_s2t&quot;,
	//    &quot;method&quot;: &quot;update_config&quot;,
	//    &quot;parameters&quot;: [
	//        {
	//            // Speech2TextConfig object
	//            &quot;s2tPipelineId&quot; : &quot;s2t_pipeline_german_1&quot;,
	//            &quot;languageModelName&quot; : &quot;language_model_german&quot;
	//        },
	//        {
	//             // condition_start object =&gt; should take effect immediately
	//             &quot;type&quot;: &quot;immediate&quot;,
	//             &quot;value&quot;: &quot;0&quot;
	//        },
	//        {
	//             // condition_end object - s2t config will be changed back to
	//             // last valid configuration after 10 interactions of user with
	//             // the AI agent
	//             &quot;type&quot;: &quot;interactions&quot;,
	//	           &quot;value&quot;: 10
	//        },
	//    ]
	//}
	//</code></pre>
	ControlMessageServiceMethod_update_config ControlMessageServiceMethod = 1
	// CSI: undo previous configuration update
	//
	// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
	// <pre><code>
	//{
	//    &quot;service&quot;: &quot;ondewo_s2t&quot;,
	//    &quot;method&quot;: &quot;undo_config&quot;,
	//    &quot;parameters&quot;: [
	//        {
	//	 	      // condition_start object
	//        },
	//        {
	//	 	      // condition_end object (OPTIONAL) - for permanent change
	//	          // no condition_end needs to be supplied i.e.
	//		      // this parameter is missing or empty &quot;{}&quot;
	//        },
	//    ]
	//}
	//</code></pre>
	ControlMessageServiceMethod_undo_config ControlMessageServiceMethod = 2
	// CSI: reset configuration to default
	//
	// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
	// <pre><code>
	//{
	//    &quot;service&quot;: &quot;ondewo_s2t&quot;,
	//    &quot;method&quot;: &quot;reset_config&quot;,
	//    &quot;parameters&quot;: [
	//        {
	//	 	      // condition_start object
	//        },
	//        {
	//	 	      // condition_end object (OPTIONAL) - for permanent change
	//            // no condition_end needs to be supplied i.e.
	//		      // this parameter is missing or empty &quot;{}&quot;
	//        },
	//    ]
	//}
	//</code></pre>
	ControlMessageServiceMethod_reset_config ControlMessageServiceMethod = 3
	// SIP: end conversation / hang up call
	//
	// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
	// <pre><code>
	//{
	//    &quot;service&quot;: &quot;ondewo_sip&quot;,
	//    &quot;method&quot;: &quot;end_call&quot;,
	//    &quot;parameters&quot;: [
	//        {
	//	 	      // condition_start object
	//        },
	//        {
	//	 	      // condition_end object (OPTIONAL) - for permanent change
	//            // no condition_end needs to be supplied i.e.
	//		      // this parameter is missing or empty &quot;{}&quot;
	//        },
	//    ]
	//}
	//</code></pre>
	ControlMessageServiceMethod_end_call ControlMessageServiceMethod = 4
	// SIP: transfer call
	//
	// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
	// <pre><code>
	//{
	//    &quot;service&quot;: &quot;ondewo_sip&quot;,
	//    &quot;method&quot;: &quot;transfer_call&quot;,
	//    &quot;parameters&quot;: [
	//        {
	//	 	      &quot;transfer_id&quot;: &quot;+43123456789@127.0.0.10:5060&quot;,
	//        },
	//        {
	//	 	      // condition_start object
	//        },
	//        {
	//	 	      // condition_end object (OPTIONAL) - for permanent change
	//            // no condition_end needs to be supplied i.e.
	//		      // this parameter is missing or empty &quot;{}&quot;
	//        },
	//    ]
	//}
	//</code></pre>
	ControlMessageServiceMethod_transfer_call ControlMessageServiceMethod = 5
	// SIP: play wav files on the call
	//
	// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
	// <pre><code>
	//{
	//    &quot;service&quot;: &quot;ondewo_sip&quot;,
	//    &quot;method&quot;: &quot;play_wav_files&quot;,
	//    &quot;parameters&quot;: [
	//        {
	//	 	      &quot;wav_files&quot;:  [
	//                &lt;bytes_of_file_1&gt;,
	//                &lt;bytes_of_file_2&gt;,
	//                &lt;bytes_of_file_3&gt;,
	//            ]
	//        },
	//        {
	//	 	      // condition_start object
	//        },
	//        {
	//	 	      // condition_end object (OPTIONAL) - for permanent change
	//            // no condition_end needs to be supplied i.e.
	//		      // this parameter is missing or empty “{}”
	//        },
	//    ]
	//}
	//</code></pre>
	ControlMessageServiceMethod_play_wav_files ControlMessageServiceMethod = 6
	// SIP: play a certain text on the phone based on Text-2-Speech synthesis
	//
	// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
	// <pre><code>
	//{
	//    &quot;service&quot;: &quot;ondewo_sip&quot;,
	//    &quot;method&quot;: &quot;play_text&quot;,
	//    &quot;parameters&quot;: [
	//        {
	//	 	      &quot;text&quot;: &quot;Welcome from ONDEWO AI Agent! How are you today?&quot;,
	//        },
	//        {
	//	 	      // condition_start object
	//        },
	//        {
	//	 	      // condition_end object (OPTIONAL) - for permanent change
	//            // no condition_end needs to be supplied i.e.
	//		      // this parameter is missing or empty &quot;{}&quot;
	//        },
	//    ]
	//}
	//</code></pre>
	ControlMessageServiceMethod_play_text ControlMessageServiceMethod = 7
	// SIP: mute microphone
	//
	// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
	// <pre><code>
	//{
	//    &quot;service&quot;: &quot;ondewo_sip&quot;,
	//    &quot;method&quot;: &quot;mute&quot;,
	//    &quot;parameters&quot;: [
	//        {
	//	 	      // condition_start object
	//        },
	//        {
	//	 	      // condition_end object (OPTIONAL) - for permanent change
	//            // no condition_end needs to be supplied i.e.
	//		      // this parameter is missing or empty &quot;{}&quot;
	//        },
	//    ]
	//}
	//</code></pre>
	ControlMessageServiceMethod_mute ControlMessageServiceMethod = 8
	// SIP: unmute microphone
	//
	// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
	// <pre><code>
	//{
	//    &quot;service&quot;: &quot;ondewo_sip&quot;,
	//    &quot;method&quot;: &quot;un_mute&quot;,
	//    &quot;parameters&quot;: [
	//        {
	//	 	      // condition_start object
	//        },
	//        {
	//	 	      // condition_end object (OPTIONAL) - for permanent change
	//            // no condition_end needs to be supplied i.e.
	//		      // this parameter is missing or empty &quot;{}&quot;
	//        },
	//    ]
	//}
	//</code></pre>
	ControlMessageServiceMethod_un_mute ControlMessageServiceMethod = 9
	// CSI: stop the execution of all running and scheduled control messages
	//
	// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
	// <pre><code>
	//{
	//    &quot;service&quot;: &quot;&quot;,    &lt;= empty string since it is for all services / no specific service
	//    &quot;method&quot;: &quot;stop_all_control_messages&quot;,
	//    "parameters": [
	//        {
	//	 	      // condition_start object
	//        },
	//        {
	//	 	      // condition_end object (OPTIONAL) - for permanent change
	//            // no condition_end needs to be supplied i.e.
	//		      // this parameter is missing or empty “{}”
	//        },
	//    ]
	//}
	//</code></pre>
	ControlMessageServiceMethod_stop_all_control_messages ControlMessageServiceMethod = 10
	// NLU: train agent
	//
	// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
	// <pre><code>
	//{
	//    &quot;service&quot;: &quot;ondewo_nlu&quot;,
	//    &quot;method&quot;: &quot;train_agent&quot;,
	//    &quot;parameters&quot;: [
	//        {
	//	 	      // condition_start object
	//        },
	//        {
	//	 	      // condition_end object (OPTIONAL) - for permanent change
	//            // no condition_end needs to be supplied i.e.
	//		      // this parameter is missing or empty &quot;{}&quot;
	//        },
	//    ]
	//}
	//</code></pre>
	ControlMessageServiceMethod_train_agent ControlMessageServiceMethod = 11
	// NLU: cancel the ongoing agent
	//
	// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
	// <pre><code>
	//{
	//    &quot;service&quot;: &quot;ondewo_nlu&quot;,
	//    &quot;method&quot;: &quot;cancel_train_agent&quot;,
	//    &quot;parameters&quot;: [
	//        {
	//	 	      // condition_start object
	//        },
	//        {
	//	 	      // condition_end object (OPTIONAL) - for permanent change
	//            // no condition_end needs to be supplied i.e.
	//		      // this parameter is missing or empty &quot;{}&quot;
	//        },
	//    ]
	//}
	//</code></pre>
	ControlMessageServiceMethod_cancel_train_agent ControlMessageServiceMethod = 12
	// NLU: delete session and all session-related information
	//
	// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
	// <pre><code>
	//{
	//    &quot;service&quot;: &quot;ondewo_nlu&quot;,
	//    &quot;method&quot;: &quot;delete_session&quot;,
	//    &quot;parameters&quot;: [
	//        {
	//	 	      &quot;session_id&quot;: &quot;97ea1a20-0784-442b-93c0-eb9e2469420e&quot;,
	//        },
	//        {
	//	 	      // condition_start object
	//        },
	//        {
	//	 	      // condition_end object (OPTIONAL) - for permanent change
	//            // no condition_end needs to be supplied i.e.
	//		      // this parameter is missing or empty &quot;{}&quot;
	//        },
	//    ]
	//}
	//</code></pre>
	ControlMessageServiceMethod_delete_session ControlMessageServiceMethod = 13
	// NLU: delete all context information in the current session
	//
	// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
	// <pre><code>
	//{
	//    &quot;service&quot;: &quot;ondewo_nlu&quot;,
	//    &quot;method&quot;: &quot;delete_all_contexts&quot;,
	//    &quot;parameters&quot;: [
	//        {
	//	 	      &quot;session_id&quot;: &quot;97ea1a20-0784-442b-93c0-eb9e2469420e&quot;,
	//        },
	//        {
	//	 	      // condition_start object
	//        },
	//        {
	//	 	      // condition_end object (OPTIONAL) - for permanent change
	//            // no condition_end needs to be supplied i.e.
	//		      // this parameter is missing or empty &quot;{}&quot;
	//        },
	//    ]
	//}
	//</code></pre>
	ControlMessageServiceMethod_delete_all_contexts ControlMessageServiceMethod = 14
	// NLU: create a context based on the provided contextual information in the current session
	//
	// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
	// <pre><code>
	//{
	//    "service": "ondewo_nlu",
	//    "method": "create_context",
	//    "parameters": [
	//        {
	//	 	      &quot;context&quot;: {           &lt;== &lt;NLU Context Object as JSON object&gt;
	//                &quot;name&quot;: &quot;projects/db46dcf8-2d2c-4115-ac38-eff443ea0e72/agent/sessions/ss2ea1a20-0784-442b-93c0-eb9e2469420e/contexts/78ea1a20-0784-442b-93c0-eb9e2469420e&quot;,
	//                ...,
	//            }
	//        },
	//        {
	//	 	      // condition_start object
	//        },
	//        {
	//	 	      // condition_end object (OPTIONAL) - for permanent change
	//            // no condition_end needs to be supplied i.e.
	//		      // this parameter is missing or empty “{}”
	//        },
	//    ]
	//}
	//</code></pre>
	ControlMessageServiceMethod_create_context ControlMessageServiceMethod = 15
	// NLU: update an existing context based on the provided contextual information in the current session
	//
	// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
	// <pre><code>
	//{
	//    "service": "ondewo_nlu",
	//    "method": "update_context",
	//    "parameters": [
	//        {
	//	 	      &quot;context&quot;: {           &lt;== &lt;NLU Context Object as JSON object&gt;
	//                &quot;name&quot;: &quot;projects/db46dcf8-2d2c-4115-ac38-eff443ea0e72/agent/sessions/2dea1a20-0784-442b-93c0-eb9e2469420e/contexts/78ea1a20-0784-442b-93c0-eb9e2469420e&quot;,
	//                ...,
	//            }
	//        },
	//        {
	//	 	      // condition_start object
	//        },
	//        {
	//	 	      // condition_end object (OPTIONAL) - for permanent change
	//            // no condition_end needs to be supplied i.e.
	//		      // this parameter is missing or empty “{}”
	//        },
	//    ]
	//}
	//</code></pre>
	ControlMessageServiceMethod_update_context ControlMessageServiceMethod = 16
	// NLU: delete an existing context including all contextual information in the current session
	//
	// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
	// <pre><code>
	//{
	//    &quot;service&quot;: &quot;ondewo_nlu&quot;,
	//    &quot;method&quot;: &quot;delete_context&quot;,
	//    &quot;parameters&quot;: [
	//        {
	//	 	      &quot;session_id&quot;: &quot;97ea1a20-0784-442b-93c0-eb9e2469420e&quot;,
	//	 	      &quot;context_name&quot;: &quot;78ea1a20-0784-442b-93c0-eb9e2469420e&quot;,
	//        },
	//        {
	//	 	      // condition_start object
	//        },
	//        {
	//	 	      // condition_end object (OPTIONAL) - for permanent change
	//            // no condition_end needs to be supplied i.e.
	//		      // this parameter is missing or empty &quot;{}&quot;
	//        },
	//    ]
	//}
	//</code></pre>
	ControlMessageServiceMethod_delete_context ControlMessageServiceMethod = 17
	// NLU: execute a detect intent request based on the provided information in the current session
	//
	// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
	// <pre><code>
	//{
	//    &quot;service&quot;: &quot;ondewo_nlu&quot;,
	//    &quot;method&quot;: &quot;detect_intent&quot;,
	//    &quot;parameters&quot;: [
	//        {
	//	 	      &quot;session_id&quot;: &quot;97ea1a20-0784-442b-93c0-eb9e2469420e&quot;,
	//	 	      &quot;text&quot;: &quot;Are you an artificial intelligence?&quot;,
	//        },
	//        {
	//	 	      // condition_start object
	//        },
	//        {
	//	 	      // condition_end object (OPTIONAL) - for permanent change
	//            // no condition_end needs to be supplied i.e.
	//		      // this parameter is missing or empty &quot;{}&quot;
	//        },
	//    ]
	//}
	//</code></pre>
	ControlMessageServiceMethod_detect_intent ControlMessageServiceMethod = 18
)

// Enum value maps for ControlMessageServiceMethod.
var (
	ControlMessageServiceMethod_name = map[int32]string{
		0:  "UNKNOWNMETHOD",
		1:  "update_config",
		2:  "undo_config",
		3:  "reset_config",
		4:  "end_call",
		5:  "transfer_call",
		6:  "play_wav_files",
		7:  "play_text",
		8:  "mute",
		9:  "un_mute",
		10: "stop_all_control_messages",
		11: "train_agent",
		12: "cancel_train_agent",
		13: "delete_session",
		14: "delete_all_contexts",
		15: "create_context",
		16: "update_context",
		17: "delete_context",
		18: "detect_intent",
	}
	ControlMessageServiceMethod_value = map[string]int32{
		"UNKNOWNMETHOD":             0,
		"update_config":             1,
		"undo_config":               2,
		"reset_config":              3,
		"end_call":                  4,
		"transfer_call":             5,
		"play_wav_files":            6,
		"play_text":                 7,
		"mute":                      8,
		"un_mute":                   9,
		"stop_all_control_messages": 10,
		"train_agent":               11,
		"cancel_train_agent":        12,
		"delete_session":            13,
		"delete_all_contexts":       14,
		"create_context":            15,
		"update_context":            16,
		"delete_context":            17,
		"detect_intent":             18,
	}
)

func (x ControlMessageServiceMethod) Enum() *ControlMessageServiceMethod {
	p := new(ControlMessageServiceMethod)
	*p = x
	return p
}

func (x ControlMessageServiceMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlMessageServiceMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_ondewo_csi_conversation_proto_enumTypes[2].Descriptor()
}

func (ControlMessageServiceMethod) Type() protoreflect.EnumType {
	return &file_ondewo_csi_conversation_proto_enumTypes[2]
}

func (x ControlMessageServiceMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlMessageServiceMethod.Descriptor instead.
func (ControlMessageServiceMethod) EnumDescriptor() ([]byte, []int) {
	return file_ondewo_csi_conversation_proto_rawDescGZIP(), []int{2}
}

// Type of condition that need to be satisfied to execute a control message.
type ConditionType int32

const (
	// Unknown type
	ConditionType_UNKNOWTYPE ConditionType = 0
	// Immediate execution of the control message. Example value need be given as a string in the format: <pre><code>value=&quot;5&quot;</code></pre>
	ConditionType_immediate ConditionType = 1
	// Duration in number of seconds after a control message should be executed. Example value need be given as a string in the format: <pre><code>value=&quot;10&quot;</code></pre>
	ConditionType_duration ConditionType = 2
	// Date and time when a control message should be executed. Example value need be given as a string in the format: <pre><code>value=&quot;2021-12-23T13:45:00.000Z&quot;</code></pre>
	ConditionType_datetime ConditionType = 3
	// Number of interactions of the user with an ONDEWO AI agent after a control message should be executed. Example value need be given as a string in the format: <pre><code>value=&quot;4&quot;</code></pre>
	ConditionType_interactions ConditionType = 4
)

// Enum value maps for ConditionType.
var (
	ConditionType_name = map[int32]string{
		0: "UNKNOWTYPE",
		1: "immediate",
		2: "duration",
		3: "datetime",
		4: "interactions",
	}
	ConditionType_value = map[string]int32{
		"UNKNOWTYPE":   0,
		"immediate":    1,
		"duration":     2,
		"datetime":     3,
		"interactions": 4,
	}
)

func (x ConditionType) Enum() *ConditionType {
	p := new(ConditionType)
	*p = x
	return p
}

func (x ConditionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConditionType) Descriptor() protoreflect.EnumDescriptor {
	return file_ondewo_csi_conversation_proto_enumTypes[3].Descriptor()
}

func (ConditionType) Type() protoreflect.EnumType {
	return &file_ondewo_csi_conversation_proto_enumTypes[3]
}

func (x ConditionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConditionType.Descriptor instead.
func (ConditionType) EnumDescriptor() ([]byte, []int) {
	return file_ondewo_csi_conversation_proto_rawDescGZIP(), []int{3}
}

// Type of SIP trigger that can be executed during a conversation.
type SipTrigger_SipTriggerType int32

const (
	// should never be used
	SipTrigger_UNSPECIFIED SipTrigger_SipTriggerType = 0
	// hard hangup
	SipTrigger_HANGUP SipTrigger_SipTriggerType = 1
	// handover to human
	SipTrigger_HUMAN_HANDOVER SipTrigger_SipTriggerType = 2
	// send now
	SipTrigger_SEND_NOW SipTrigger_SipTriggerType = 3
	// pause
	SipTrigger_PAUSE SipTrigger_SipTriggerType = 4
	// transfer
	SipTrigger_TRANSFER SipTrigger_SipTriggerType = 5
	// invite to conference call
	SipTrigger_INVITE SipTrigger_SipTriggerType = 6
	// play audio
	SipTrigger_PLAY_AUDIO SipTrigger_SipTriggerType = 7
)

// Enum value maps for SipTrigger_SipTriggerType.
var (
	SipTrigger_SipTriggerType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "HANGUP",
		2: "HUMAN_HANDOVER",
		3: "SEND_NOW",
		4: "PAUSE",
		5: "TRANSFER",
		6: "INVITE",
		7: "PLAY_AUDIO",
	}
	SipTrigger_SipTriggerType_value = map[string]int32{
		"UNSPECIFIED":    0,
		"HANGUP":         1,
		"HUMAN_HANDOVER": 2,
		"SEND_NOW":       3,
		"PAUSE":          4,
		"TRANSFER":       5,
		"INVITE":         6,
		"PLAY_AUDIO":     7,
	}
)

func (x SipTrigger_SipTriggerType) Enum() *SipTrigger_SipTriggerType {
	p := new(SipTrigger_SipTriggerType)
	*p = x
	return p
}

func (x SipTrigger_SipTriggerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SipTrigger_SipTriggerType) Descriptor() protoreflect.EnumDescriptor {
	return file_ondewo_csi_conversation_proto_enumTypes[4].Descriptor()
}

func (SipTrigger_SipTriggerType) Type() protoreflect.EnumType {
	return &file_ondewo_csi_conversation_proto_enumTypes[4]
}

func (x SipTrigger_SipTriggerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SipTrigger_SipTriggerType.Descriptor instead.
func (SipTrigger_SipTriggerType) EnumDescriptor() ([]byte, []int) {
	return file_ondewo_csi_conversation_proto_rawDescGZIP(), []int{6, 0}
}

// The top-level message sent by client to <code>CreateS2sPipeline</code> and <code>UpdateS2sPipeline</code> endpoints and received from <code>GetS2sPipeline</code> endpoint.
type S2SPipeline struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. CSI pipeline identifier consisting of S2T, NLU and T2S configuration. ID can be any non-empty string.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Required. S2T pipeline ID, e.g. "german_general"
	S2TPipelineId string `protobuf:"bytes,2,opt,name=s2t_pipeline_id,json=s2tPipelineId,proto3" json:"s2t_pipeline_id,omitempty"`
	// Required. NLU project ID, usually a hash, e.g. "ae33586b-x2s2-494a-aa73-1af0589cfc56".
	NluProjectId string `protobuf:"bytes,3,opt,name=nlu_project_id,json=nluProjectId,proto3" json:"nlu_project_id,omitempty"`
	// Required. Language code present in the corresponding NLU project, e.g. "de".
	NluLanguageCode string `protobuf:"bytes,4,opt,name=nlu_language_code,json=nluLanguageCode,proto3" json:"nlu_language_code,omitempty"`
	// Required. T2S pipeline ID, e.g. "kerstin".
	T2SPipelineId string `protobuf:"bytes,5,opt,name=t2s_pipeline_id,json=t2sPipelineId,proto3" json:"t2s_pipeline_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2SPipeline) Reset() {
	*x = S2SPipeline{}
	mi := &file_ondewo_csi_conversation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2SPipeline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2SPipeline) ProtoMessage() {}

func (x *S2SPipeline) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_csi_conversation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2SPipeline.ProtoReflect.Descriptor instead.
func (*S2SPipeline) Descriptor() ([]byte, []int) {
	return file_ondewo_csi_conversation_proto_rawDescGZIP(), []int{0}
}

func (x *S2SPipeline) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *S2SPipeline) GetS2TPipelineId() string {
	if x != nil {
		return x.S2TPipelineId
	}
	return ""
}

func (x *S2SPipeline) GetNluProjectId() string {
	if x != nil {
		return x.NluProjectId
	}
	return ""
}

func (x *S2SPipeline) GetNluLanguageCode() string {
	if x != nil {
		return x.NluLanguageCode
	}
	return ""
}

func (x *S2SPipeline) GetT2SPipelineId() string {
	if x != nil {
		return x.T2SPipelineId
	}
	return ""
}

// The top-level message sent by client to <code>GetS2sPipeline</code> and <code>DeleteS2sPipeline</code> endpoints.
type S2SPipelineId struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. CSI pipeline identifier.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2SPipelineId) Reset() {
	*x = S2SPipelineId{}
	mi := &file_ondewo_csi_conversation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2SPipelineId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2SPipelineId) ProtoMessage() {}

func (x *S2SPipelineId) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_csi_conversation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2SPipelineId.ProtoReflect.Descriptor instead.
func (*S2SPipelineId) Descriptor() ([]byte, []int) {
	return file_ondewo_csi_conversation_proto_rawDescGZIP(), []int{1}
}

func (x *S2SPipelineId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// The top-level message sent by client to <code>ListS2sPipelines</code> endpoint. Currently without arguments.
type ListS2SPipelinesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListS2SPipelinesRequest) Reset() {
	*x = ListS2SPipelinesRequest{}
	mi := &file_ondewo_csi_conversation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListS2SPipelinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListS2SPipelinesRequest) ProtoMessage() {}

func (x *ListS2SPipelinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_csi_conversation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListS2SPipelinesRequest.ProtoReflect.Descriptor instead.
func (*ListS2SPipelinesRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_csi_conversation_proto_rawDescGZIP(), []int{2}
}

// The top-level message received from <code>ListS2sPipelines</code> endpoint.
type ListS2SPipelinesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Collection of S2S pipelines of the server.
	Pipelines     []*S2SPipeline `protobuf:"bytes,1,rep,name=pipelines,proto3" json:"pipelines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListS2SPipelinesResponse) Reset() {
	*x = ListS2SPipelinesResponse{}
	mi := &file_ondewo_csi_conversation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListS2SPipelinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListS2SPipelinesResponse) ProtoMessage() {}

func (x *ListS2SPipelinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_csi_conversation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListS2SPipelinesResponse.ProtoReflect.Descriptor instead.
func (*ListS2SPipelinesResponse) Descriptor() ([]byte, []int) {
	return file_ondewo_csi_conversation_proto_rawDescGZIP(), []int{3}
}

func (x *ListS2SPipelinesResponse) GetPipelines() []*S2SPipeline {
	if x != nil {
		return x.Pipelines
	}
	return nil
}

// The top-level message sent by the client to the <code>S2sStream</code> method.
// Multiple request messages should be sent in order:
// <ul>
//
//	<li>The first message must contain <code>pipeline_id</code> and can contain <code>session_id</code> or <code>initial_intent_display_name</code>. The message must not contain <code>audio</code> nor <code>end_of_stream</code>.</li>
//	<li>All subsequent messages must contain <code>audio</code>. If <code>end_of_stream</code> is <code>true</code>, the stream is closed.</li>
//
// </ul>
type S2SStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. The CSI pipeline ID specified in the initial request.
	PipelineId string `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	// <p>Optional. The session or call ID specified in the initial request. It&apos;s up to the API caller to choose an appropriate string. It can be a random number or some type of user identifier (preferably hashed).</p>
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Optional. The input audio content to be recognized.
	Audio []byte `protobuf:"bytes,3,opt,name=audio,proto3" json:"audio,omitempty"`
	// If <code>true</code>, the recognizer will not return any further hypotheses about this piece of the audio. May only be populated for <code>event_type</code> = <code>RECOGNITION_EVENT_TRANSCRIPT</code>.
	EndOfStream bool `protobuf:"varint,4,opt,name=end_of_stream,json=endOfStream,proto3" json:"end_of_stream,omitempty"`
	// Optional. Intent display name to trigger in NLU system in the beginning of the conversation.
	InitialIntentDisplayName string `protobuf:"bytes,5,opt,name=initial_intent_display_name,json=initialIntentDisplayName,proto3" json:"initial_intent_display_name,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *S2SStreamRequest) Reset() {
	*x = S2SStreamRequest{}
	mi := &file_ondewo_csi_conversation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2SStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2SStreamRequest) ProtoMessage() {}

func (x *S2SStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_csi_conversation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2SStreamRequest.ProtoReflect.Descriptor instead.
func (*S2SStreamRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_csi_conversation_proto_rawDescGZIP(), []int{4}
}

func (x *S2SStreamRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *S2SStreamRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *S2SStreamRequest) GetAudio() []byte {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *S2SStreamRequest) GetEndOfStream() bool {
	if x != nil {
		return x.EndOfStream
	}
	return false
}

func (x *S2SStreamRequest) GetInitialIntentDisplayName() string {
	if x != nil {
		return x.InitialIntentDisplayName
	}
	return ""
}

// The top-level message returned from the <code>S2sStream</code> method.
// A response message is returned for each utterance of the input stream. It contains the full response from NLU system in <code>detect_intent_response</code> or the full T2S response in <code>synthesize_response</code>.
// Multiple response messages can be returned in order:
// <ul>
//
//	<li>The first response message for an input utterance contains response from NLU system <code>detect_intent_response</code> with detected intent and N fulfillment messages (N &gt;= 0).</li>
//	<li>The next N response messages contain for each fulfillment message one of the following:
//	  <ul>
//	    <li>T2S response <code>synthesize_response</code> with synthesized audio</li>
//	    <li>SIP trigger message <code>sip_trigger</code> with SIP trigger extracted from the fulfillment message</li>
//	  </ul>
//	</li>
//
// </ul>
type S2SStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Response type for the S2S stream. One of the following will be populated.
	//
	// Types that are valid to be assigned to Response:
	//
	//	*S2SStreamResponse_DetectIntentResponse
	//	*S2SStreamResponse_SynthesizeResponse
	//	*S2SStreamResponse_SipTrigger
	Response isS2SStreamResponse_Response `protobuf_oneof:"response"`
	// Optional. Identifier of the utterance this response belongs to. All chunks of one synthesized utterance share the same <code>utterance_id</code>
	UtteranceId string `protobuf:"bytes,4,opt,name=utterance_id,json=utteranceId,proto3" json:"utterance_id,omitempty"`
	// Optional. Zero-based index of this chunk within the utterance identified by <code>utterance_id</code>
	ChunkIndex int32 `protobuf:"varint,5,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	// Optional. If <code>true</code>, this is the last chunk of the utterance identified by <code>utterance_id</code>
	LastChunk bool `protobuf:"varint,6,opt,name=last_chunk,json=lastChunk,proto3" json:"last_chunk,omitempty"`
	// Optional. Monotonic turn epoch of the conversation turn that produced this response. Used by consumers to fence stale audio of an interrupted turn
	TurnEpoch     uint64 `protobuf:"varint,7,opt,name=turn_epoch,json=turnEpoch,proto3" json:"turn_epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2SStreamResponse) Reset() {
	*x = S2SStreamResponse{}
	mi := &file_ondewo_csi_conversation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2SStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2SStreamResponse) ProtoMessage() {}

func (x *S2SStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_csi_conversation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2SStreamResponse.ProtoReflect.Descriptor instead.
func (*S2SStreamResponse) Descriptor() ([]byte, []int) {
	return file_ondewo_csi_conversation_proto_rawDescGZIP(), []int{5}
}

func (x *S2SStreamResponse) GetResponse() isS2SStreamResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *S2SStreamResponse) GetDetectIntentResponse() *nlu.DetectIntentResponse {
	if x != nil {
		if x, ok := x.Response.(*S2SStreamResponse_DetectIntentResponse); ok {
			return x.DetectIntentResponse
		}
	}
	return nil
}

func (x *S2SStreamResponse) GetSynthesizeResponse() *t2s.SynthesizeResponse {
	if x != nil {
		if x, ok := x.Response.(*S2SStreamResponse_SynthesizeResponse); ok {
			return x.SynthesizeResponse
		}
	}
	return nil
}

func (x *S2SStreamResponse) GetSipTrigger() *SipTrigger {
	if x != nil {
		if x, ok := x.Response.(*S2SStreamResponse_SipTrigger); ok {
			return x.SipTrigger
		}
	}
	return nil
}

func (x *S2SStreamResponse) GetUtteranceId() string {
	if x != nil {
		return x.UtteranceId
	}
	return ""
}

func (x *S2SStreamResponse) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *S2SStreamResponse) GetLastChunk() bool {
	if x != nil {
		return x.LastChunk
	}
	return false
}

func (x *S2SStreamResponse) GetTurnEpoch() uint64 {
	if x != nil {
		return x.TurnEpoch
	}
	return 0
}

type isS2SStreamResponse_Response interface {
	isS2SStreamResponse_Response()
}

type S2SStreamResponse_DetectIntentResponse struct {
	// full NLU detect intent response
	DetectIntentResponse *nlu.DetectIntentResponse `protobuf:"bytes,1,opt,name=detect_intent_response,json=detectIntentResponse,proto3,oneof"`
}

type S2SStreamResponse_SynthesizeResponse struct {
	// full T2S synthesize response
	SynthesizeResponse *t2s.SynthesizeResponse `protobuf:"bytes,2,opt,name=synthesize_response,json=synthesizeResponse,proto3,oneof"`
}

type S2SStreamResponse_SipTrigger struct {
	// SIP trigger message
	SipTrigger *SipTrigger `protobuf:"bytes,3,opt,name=sip_trigger,json=sipTrigger,proto3,oneof"`
}

func (*S2SStreamResponse_DetectIntentResponse) isS2SStreamResponse_Response() {}

func (*S2SStreamResponse_SynthesizeResponse) isS2SStreamResponse_Response() {}

func (*S2SStreamResponse_SipTrigger) isS2SStreamResponse_Response() {}

// SIP trigger message.
type SipTrigger struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of the SIP trigger.
	Type SipTrigger_SipTriggerType `protobuf:"varint,1,opt,name=type,proto3,enum=ondewo.csi.SipTrigger_SipTriggerType" json:"type,omitempty"`
	// extra parameters for the trigger
	Content       *structpb.Struct `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SipTrigger) Reset() {
	*x = SipTrigger{}
	mi := &file_ondewo_csi_conversation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SipTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SipTrigger) ProtoMessage() {}

func (x *SipTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_csi_conversation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SipTrigger.ProtoReflect.Descriptor instead.
func (*SipTrigger) Descriptor() ([]byte, []int) {
	return file_ondewo_csi_conversation_proto_rawDescGZIP(), []int{6}
}

func (x *SipTrigger) GetType() SipTrigger_SipTriggerType {
	if x != nil {
		return x.Type
	}
	return SipTrigger_UNSPECIFIED
}

func (x *SipTrigger) GetContent() *structpb.Struct {
	if x != nil {
		return x.Content
	}
	return nil
}

// Health checks.
type CheckUpstreamHealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Health checks for Speech-2-Text
	S2TStatus *status.Status `protobuf:"bytes,1,opt,name=s2t_status,json=s2tStatus,proto3" json:"s2t_status,omitempty"`
	// Health checks for NLU
	NluStatus *status.Status `protobuf:"bytes,2,opt,name=nlu_status,json=nluStatus,proto3" json:"nlu_status,omitempty"`
	// Health checks for Text-2-Speech
	T2SStatus     *status.Status `protobuf:"bytes,3,opt,name=t2s_status,json=t2sStatus,proto3" json:"t2s_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUpstreamHealthResponse) Reset() {
	*x = CheckUpstreamHealthResponse{}
	mi := &file_ondewo_csi_conversation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUpstreamHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUpstreamHealthResponse) ProtoMessage() {}

func (x *CheckUpstreamHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_csi_conversation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUpstreamHealthResponse.ProtoReflect.Descriptor instead.
func (*CheckUpstreamHealthResponse) Descriptor() ([]byte, []int) {
	return file_ondewo_csi_conversation_proto_rawDescGZIP(), []int{7}
}

func (x *CheckUpstreamHealthResponse) GetS2TStatus() *status.Status {
	if x != nil {
		return x.S2TStatus
	}
	return nil
}

func (x *CheckUpstreamHealthResponse) GetNluStatus() *status.Status {
	if x != nil {
		return x.NluStatus
	}
	return nil
}

func (x *CheckUpstreamHealthResponse) GetT2SStatus() *status.Status {
	if x != nil {
		return x.T2SStatus
	}
	return nil
}

// Control stream message.
type ControlStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlStreamRequest) Reset() {
	*x = ControlStreamRequest{}
	mi := &file_ondewo_csi_conversation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlStreamRequest) ProtoMessage() {}

func (x *ControlStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_csi_conversation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlStreamRequest.ProtoReflect.Descriptor instead.
func (*ControlStreamRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_csi_conversation_proto_rawDescGZIP(), []int{8}
}

// Control stream response message.
type ControlStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Control status
	ControlStatus ControlStatus `protobuf:"varint,1,opt,name=control_status,json=controlStatus,proto3,enum=ondewo.csi.ControlStatus" json:"control_status,omitempty"`
	// Monotonic barge-in epoch/sequence number so control status transitions are correlatable with the <code>S2sStreamResponse</code> <code>turn_epoch</code> and a second barge-in during a resumed remainder can never be coalesced away
	Epoch         uint64 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlStreamResponse) Reset() {
	*x = ControlStreamResponse{}
	mi := &file_ondewo_csi_conversation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlStreamResponse) ProtoMessage() {}

func (x *ControlStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_csi_conversation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlStreamResponse.ProtoReflect.Descriptor instead.
func (*ControlStreamResponse) Descriptor() ([]byte, []int) {
	return file_ondewo_csi_conversation_proto_rawDescGZIP(), []int{9}
}

func (x *ControlStreamResponse) GetControlStatus() ControlStatus {
	if x != nil {
		return x.ControlStatus
	}
	return ControlStatus_OK
}

func (x *ControlStreamResponse) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

// Request to set control status.
type SetControlStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Control status
	ControlStatus ControlStatus `protobuf:"varint,1,opt,name=control_status,json=controlStatus,proto3,enum=ondewo.csi.ControlStatus" json:"control_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetControlStatusRequest) Reset() {
	*x = SetControlStatusRequest{}
	mi := &file_ondewo_csi_conversation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetControlStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetControlStatusRequest) ProtoMessage() {}

func (x *SetControlStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_csi_conversation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetControlStatusRequest.ProtoReflect.Descriptor instead.
func (*SetControlStatusRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_csi_conversation_proto_rawDescGZIP(), []int{10}
}

func (x *SetControlStatusRequest) GetControlStatus() ControlStatus {
	if x != nil {
		return x.ControlStatus
	}
	return ControlStatus_OK
}

// Response of setting the control status with the old and new status objects.
type SetControlStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Previous 'old' control status
	OldControlStatus ControlStatus `protobuf:"varint,1,opt,name=old_control_status,json=oldControlStatus,proto3,enum=ondewo.csi.ControlStatus" json:"old_control_status,omitempty"`
	// Current 'new' control status
	NewControlStatus ControlStatus `protobuf:"varint,2,opt,name=new_control_status,json=newControlStatus,proto3,enum=ondewo.csi.ControlStatus" json:"new_control_status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SetControlStatusResponse) Reset() {
	*x = SetControlStatusResponse{}
	mi := &file_ondewo_csi_conversation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetControlStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetControlStatusResponse) ProtoMessage() {}

func (x *SetControlStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_csi_conversation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetControlStatusResponse.ProtoReflect.Descriptor instead.
func (*SetControlStatusResponse) Descriptor() ([]byte, []int) {
	return file_ondewo_csi_conversation_proto_rawDescGZIP(), []int{11}
}

func (x *SetControlStatusResponse) GetOldControlStatus() ControlStatus {
	if x != nil {
		return x.OldControlStatus
	}
	return ControlStatus_OK
}

func (x *SetControlStatusResponse) GetNewControlStatus() ControlStatus {
	if x != nil {
		return x.NewControlStatus
	}
	return ControlStatus_OK
}

// A condition message with its type and value.
// A Condition can be of various types.
// Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:
// Immediate execution:
// <pre><code>
//
//	{
//	   &quot;type&quot;: &quot;immediate&quot;
//	}
//
// </code></pre>
// Number of interactions of the user with the AI agent:
// <pre><code>
//
//	{
//	   &quot;type&quot;: &quot;interactions&quot;,
//	   &quot;value&quot;: &quot;10&quot;
//	}
//
// </code></pre>
// Number of seconds:
// <pre><code>
//
//	{
//	   &quot;type&quot;: &quot;duration&quot;,
//	   &quot;value&quot;: &quot;3600&quot;
//	}
//
// </code></pre>
// At a specific date and time:
// <pre><code>
//
//	{
//	   &quot;type&quot;: &quot;datetime&quot;,
//	   &quot;value&quot;: &quot;2021-12-23T13:45:00.000Z&quot;
//	}
//
// </code></pre>
type Condition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Condition type
	Type ConditionType `protobuf:"varint,1,opt,name=type,proto3,enum=ondewo.csi.ConditionType" json:"type,omitempty"`
	// Value of the condition. Examples of conditions values based on the condition type are given in the <code>ConditionType</code> documentation.
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_ondewo_csi_conversation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_csi_conversation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_ondewo_csi_conversation_proto_rawDescGZIP(), []int{12}
}

func (x *Condition) GetType() ConditionType {
	if x != nil {
		return x.Type
	}
	return ConditionType_UNKNOWTYPE
}

func (x *Condition) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Parameters of the control message passed to the service specified in the control message.
type ControlMessageServiceParameters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Configuration
	//
	// Types that are valid to be assigned to Config:
	//
	//	*ControlMessageServiceParameters_T2SConfig
	//	*ControlMessageServiceParameters_S2TConfig
	Config isControlMessageServiceParameters_Config `protobuf_oneof:"config"`
	// SIP: callee id to transfer call to
	TransferId string `protobuf:"bytes,3,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	// SIP: bytes of audio files to play to a caller
	WavFiles [][]byte `protobuf:"bytes,4,rep,name=wav_files,json=wavFiles,proto3" json:"wav_files,omitempty"`
	// text, e.g. for NLU detect intent response or Text-2-Speech voice synthesis
	Text string `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	// NLU: context for creating, updating or deleting contextual information from a NLU session
	Context *nlu.Context `protobuf:"bytes,6,opt,name=context,proto3" json:"context,omitempty"`
	// NLU: the session id of a NLU session
	SessionId string `protobuf:"bytes,7,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// NLU: the name of the context of a NLU session
	ContextName string `protobuf:"bytes,8,opt,name=context_name,json=contextName,proto3" json:"context_name,omitempty"`
	// CSI: the condition that defines when a control message should be executed
	ConditionStart *Condition `protobuf:"bytes,9,opt,name=condition_start,json=conditionStart,proto3" json:"condition_start,omitempty"`
	// CSI: the condition that defines when a control message should stop its execution
	ConditionEnd  *Condition `protobuf:"bytes,10,opt,name=condition_end,json=conditionEnd,proto3" json:"condition_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessageServiceParameters) Reset() {
	*x = ControlMessageServiceParameters{}
	mi := &file_ondewo_csi_conversation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessageServiceParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessageServiceParameters) ProtoMessage() {}

func (x *ControlMessageServiceParameters) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_csi_conversation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessageServiceParameters.ProtoReflect.Descriptor instead.
func (*ControlMessageServiceParameters) Descriptor() ([]byte, []int) {
	return file_ondewo_csi_conversation_proto_rawDescGZIP(), []int{13}
}

func (x *ControlMessageServiceParameters) GetConfig() isControlMessageServiceParameters_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ControlMessageServiceParameters) GetT2SConfig() *t2s.RequestConfig {
	if x != nil {
		if x, ok := x.Config.(*ControlMessageServiceParameters_T2SConfig); ok {
			return x.T2SConfig
		}
	}
	return nil
}

func (x *ControlMessageServiceParameters) GetS2TConfig() *s2t.TranscribeRequestConfig {
	if x != nil {
		if x, ok := x.Config.(*ControlMessageServiceParameters_S2TConfig); ok {
			return x.S2TConfig
		}
	}
	return nil
}

func (x *ControlMessageServiceParameters) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *ControlMessageServiceParameters) GetWavFiles() [][]byte {
	if x != nil {
		return x.WavFiles
	}
	return nil
}

func (x *ControlMessageServiceParameters) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ControlMessageServiceParameters) GetContext() *nlu.Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ControlMessageServiceParameters) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ControlMessageServiceParameters) GetContextName() string {
	if x != nil {
		return x.ContextName
	}
	return ""
}

func (x *ControlMessageServiceParameters) GetConditionStart() *Condition {
	if x != nil {
		return x.ConditionStart
	}
	return nil
}

func (x *ControlMessageServiceParameters) GetConditionEnd() *Condition {
	if x != nil {
		return x.ConditionEnd
	}
	return nil
}

type isControlMessageServiceParameters_Config interface {
	isControlMessageServiceParameters_Config()
}

type ControlMessageServiceParameters_T2SConfig struct {
	// Text-2-Speech: configuration to control the synthesis of a text into audio
	T2SConfig *t2s.RequestConfig `protobuf:"bytes,1,opt,name=t2s_config,json=t2sConfig,proto3,oneof"`
}

type ControlMessageServiceParameters_S2TConfig struct {
	// Speech-2-Text: configuration to control the recognition of text based on human voice audio
	S2TConfig *s2t.TranscribeRequestConfig `protobuf:"bytes,2,opt,name=s2t_config,json=s2tConfig,proto3,oneof"`
}

func (*ControlMessageServiceParameters_T2SConfig) isControlMessageServiceParameters_Config() {}

func (*ControlMessageServiceParameters_S2TConfig) isControlMessageServiceParameters_Config() {}

// A control message.
// Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:
// <pre><code>
//
//	{
//	  &quot;service&quot;: &quot;&lt;SERVICE_NAME&gt;&quot;, 			// e.g. ondewo_s2t
//	  &quot;method&quot;: &quot;&lt;SERVICE_CONTROL_METHOD&gt;&quot;, 	// e.g. update_config
//	  &quot;parameters&quot;: [
//	      // primitive data types and JSON objects are possible
//	      1,
//	      1.0,
//	      -2.0,
//	      &quot;string&quot;,
//	      true,
//	  	 {
//	          // parameter JSON object
//	      },
//	      {
//	          // Condition start object
//	      },
//	      {
//	          // Condition end object [optional]
//	      },
//	   ]
//	}
//
// </code></pre>
type ControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service to control. Valid service names are: <code>ondewo_nlu</code>, <code>ondewo_t2s</code>, <code>ondewo_s2t</code>, <code>ondewo_sip</code> and <code>ondewo_csi</code>.
	Service ControlMessageServiceName `protobuf:"varint,1,opt,name=service,proto3,enum=ondewo.csi.ControlMessageServiceName" json:"service,omitempty"`
	// Method to invoke on the service
	Method ControlMessageServiceMethod `protobuf:"varint,2,opt,name=method,proto3,enum=ondewo.csi.ControlMessageServiceMethod" json:"method,omitempty"`
	// Parameters to use to invoke the method of the service
	Parameters    *ControlMessageServiceParameters `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_ondewo_csi_conversation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_csi_conversation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_ondewo_csi_conversation_proto_rawDescGZIP(), []int{14}
}

func (x *ControlMessage) GetService() ControlMessageServiceName {
	if x != nil {
		return x.Service
	}
	return ControlMessageServiceName_UNKNOWNNAME
}

func (x *ControlMessage) GetMethod() ControlMessageServiceMethod {
	if x != nil {
		return x.Method
	}
	return ControlMessageServiceMethod_UNKNOWNMETHOD
}

func (x *ControlMessage) GetParameters() *ControlMessageServiceParameters {
	if x != nil {
		return x.Parameters
	}
	return nil
}

var File_ondewo_csi_conversation_proto protoreflect.FileDescriptor

const file_ondewo_csi_conversation_proto_rawDesc = "" +
	"\n" +
	"\x1dondewo/csi/conversation.proto\x12\n" +
	"ondewo.csi\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17google/rpc/status.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x18ondewo/nlu/session.proto\x1a\x1fondewo/t2s/text-to-speech.proto\x1a\x1fondewo/s2t/speech-to-text.proto\x1a\x18ondewo/nlu/context.proto\x1a\x19google/protobuf/any.proto\"\xbf\x01\n" +
	"\vS2sPipeline\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x0fs2t_pipeline_id\x18\x02 \x01(\tR\rs2tPipelineId\x12$\n" +
	"\x0enlu_project_id\x18\x03 \x01(\tR\fnluProjectId\x12*\n" +
	"\x11nlu_language_code\x18\x04 \x01(\tR\x0fnluLanguageCode\x12&\n" +
	"\x0ft2s_pipeline_id\x18\x05 \x01(\tR\rt2sPipelineId\"\x1f\n" +
	"\rS2sPipelineId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x19\n" +
	"\x17ListS2sPipelinesRequest\"Q\n" +
	"\x18ListS2sPipelinesResponse\x125\n" +
	"\tpipelines\x18\x01 \x03(\v2\x17.ondewo.csi.S2sPipelineR\tpipelines\"\xcb\x01\n" +
	"\x10S2sStreamRequest\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05audio\x18\x03 \x01(\fR\x05audio\x12\"\n" +
	"\rend_of_stream\x18\x04 \x01(\bR\vendOfStream\x12=\n" +
	"\x1binitial_intent_display_name\x18\x05 \x01(\tR\x18initialIntentDisplayName\"\x89\x03\n" +
	"\x11S2sStreamResponse\x12X\n" +
	"\x16detect_intent_response\x18\x01 \x01(\v2 .ondewo.nlu.DetectIntentResponseH\x00R\x14detectIntentResponse\x12Q\n" +
	"\x13synthesize_response\x18\x02 \x01(\v2\x1e.ondewo.t2s.SynthesizeResponseH\x00R\x12synthesizeResponse\x129\n" +
	"\vsip_trigger\x18\x03 \x01(\v2\x16.ondewo.csi.SipTriggerH\x00R\n" +
	"sipTrigger\x12!\n" +
	"\futterance_id\x18\x04 \x01(\tR\vutteranceId\x12\x1f\n" +
	"\vchunk_index\x18\x05 \x01(\x05R\n" +
	"chunkIndex\x12\x1d\n" +
	"\n" +
	"last_chunk\x18\x06 \x01(\bR\tlastChunk\x12\x1d\n" +
	"\n" +
	"turn_epoch\x18\a \x01(\x04R\tturnEpochB\n" +
	"\n" +
	"\bresponse\"\x81\x02\n" +
	"\n" +
	"SipTrigger\x129\n" +
	"\x04type\x18\x01 \x01(\x0e2%.ondewo.csi.SipTrigger.SipTriggerTypeR\x04type\x121\n" +
	"\acontent\x18\x02 \x01(\v2\x17.google.protobuf.StructR\acontent\"\x84\x01\n" +
	"\x0eSipTriggerType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06HANGUP\x10\x01\x12\x12\n" +
	"\x0eHUMAN_HANDOVER\x10\x02\x12\f\n" +
	"\bSEND_NOW\x10\x03\x12\t\n" +
	"\x05PAUSE\x10\x04\x12\f\n" +
	"\bTRANSFER\x10\x05\x12\n" +
	"\n" +
	"\x06INVITE\x10\x06\x12\x0e\n" +
	"\n" +
	"PLAY_AUDIO\x10\a\"\xb6\x01\n" +
	"\x1bCheckUpstreamHealthResponse\x121\n" +
	"\n" +
	"s2t_status\x18\x01 \x01(\v2\x12.google.rpc.StatusR\ts2tStatus\x121\n" +
	"\n" +
	"nlu_status\x18\x02 \x01(\v2\x12.google.rpc.StatusR\tnluStatus\x121\n" +
	"\n" +
	"t2s_status\x18\x03 \x01(\v2\x12.google.rpc.StatusR\tt2sStatus\"\x16\n" +
	"\x14ControlStreamRequest\"o\n" +
	"\x15ControlStreamResponse\x12@\n" +
	"\x0econtrol_status\x18\x01 \x01(\x0e2\x19.ondewo.csi.ControlStatusR\rcontrolStatus\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\"[\n" +
	"\x17SetControlStatusRequest\x12@\n" +
	"\x0econtrol_status\x18\x01 \x01(\x0e2\x19.ondewo.csi.ControlStatusR\rcontrolStatus\"\xac\x01\n" +
	"\x18SetControlStatusResponse\x12G\n" +
	"\x12old_control_status\x18\x01 \x01(\x0e2\x19.ondewo.csi.ControlStatusR\x10oldControlStatus\x12G\n" +
	"\x12new_control_status\x18\x02 \x01(\x0e2\x19.ondewo.csi.ControlStatusR\x10newControlStatus\"P\n" +
	"\tCondition\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.ondewo.csi.ConditionTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xec\x03\n" +
	"\x1fControlMessageServiceParameters\x12:\n" +
	"\n" +
	"t2s_config\x18\x01 \x01(\v2\x19.ondewo.t2s.RequestConfigH\x00R\tt2sConfig\x12D\n" +
	"\n" +
	"s2t_config\x18\x02 \x01(\v2#.ondewo.s2t.TranscribeRequestConfigH\x00R\ts2tConfig\x12\x1f\n" +
	"\vtransfer_id\x18\x03 \x01(\tR\n" +
	"transferId\x12\x1b\n" +
	"\twav_files\x18\x04 \x03(\fR\bwavFiles\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12-\n" +
	"\acontext\x18\x06 \x01(\v2\x13.ondewo.nlu.ContextR\acontext\x12\x1d\n" +
	"\n" +
	"session_id\x18\a \x01(\tR\tsessionId\x12!\n" +
	"\fcontext_name\x18\b \x01(\tR\vcontextName\x12>\n" +
	"\x0fcondition_start\x18\t \x01(\v2\x15.ondewo.csi.ConditionR\x0econditionStart\x12:\n" +
	"\rcondition_end\x18\n" +
	" \x01(\v2\x15.ondewo.csi.ConditionR\fconditionEndB\b\n" +
	"\x06config\"\xdf\x01\n" +
	"\x0eControlMessage\x12?\n" +
	"\aservice\x18\x01 \x01(\x0e2%.ondewo.csi.ControlMessageServiceNameR\aservice\x12?\n" +
	"\x06method\x18\x02 \x01(\x0e2'.ondewo.csi.ControlMessageServiceMethodR\x06method\x12K\n" +
	"\n" +
	"parameters\x18\x03 \x01(\v2+.ondewo.csi.ControlMessageServiceParametersR\n" +
	"parameters*\xb7\x01\n" +
	"\rControlStatus\x12\x06\n" +
	"\x02OK\x10\x00\x12\x12\n" +
	"\x0eEMERGENCY_STOP\x10\x01\x12\x17\n" +
	"\x13VAD_START_OF_SPEECH\x10\x02\x12\f\n" +
	"\bBARGE_IN\x10\x03\x12\x13\n" +
	"\x0fRESUME_PLAYBACK\x10\x04\x12\x15\n" +
	"\x11DISCARD_REMAINDER\x10\x05\x12\x14\n" +
	"\x10PLAYBACK_RESUMED\x10\x06\x12\x11\n" +
	"\rPLAYBACK_DONE\x10\a\x12\x0e\n" +
	"\n" +
	"CALL_ENDED\x10\b*\xa0\x01\n" +
	"\x19ControlMessageServiceName\x12\x0f\n" +
	"\vUNKNOWNNAME\x10\x00\x12\x0e\n" +
	"\n" +
	"ondewo_s2t\x10\x01\x12\x0e\n" +
	"\n" +
	"ondewo_t2s\x10\x02\x12\x0e\n" +
	"\n" +
	"ondewo_nlu\x10\x03\x12\x0e\n" +
	"\n" +
	"ondewo_sip\x10\x04\x12\x0f\n" +
	"\vondewo_vtsi\x10\x05\x12\x0e\n" +
	"\n" +
	"ondewo_csi\x10\x06\x12\x11\n" +
	"\rondewo_survey\x10\a*\x85\x03\n" +
	"\x1bControlMessageServiceMethod\x12\x11\n" +
	"\rUNKNOWNMETHOD\x10\x00\x12\x11\n" +
	"\rupdate_config\x10\x01\x12\x0f\n" +
	"\vundo_config\x10\x02\x12\x10\n" +
	"\freset_config\x10\x03\x12\f\n" +
	"\bend_call\x10\x04\x12\x11\n" +
	"\rtransfer_call\x10\x05\x12\x12\n" +
	"\x0eplay_wav_files\x10\x06\x12\r\n" +
	"\tplay_text\x10\a\x12\b\n" +
	"\x04mute\x10\b\x12\v\n" +
	"\aun_mute\x10\t\x12\x1d\n" +
	"\x19stop_all_control_messages\x10\n" +
	"\x12\x0f\n" +
	"\vtrain_agent\x10\v\x12\x16\n" +
	"\x12cancel_train_agent\x10\f\x12\x12\n" +
	"\x0edelete_session\x10\r\x12\x17\n" +
	"\x13delete_all_contexts\x10\x0e\x12\x12\n" +
	"\x0ecreate_context\x10\x0f\x12\x12\n" +
	"\x0eupdate_context\x10\x10\x12\x12\n" +
	"\x0edelete_context\x10\x11\x12\x11\n" +
	"\rdetect_intent\x10\x12*\\\n" +
	"\rConditionType\x12\x0e\n" +
	"\n" +
	"UNKNOWTYPE\x10\x00\x12\r\n" +
	"\timmediate\x10\x01\x12\f\n" +
	"\bduration\x10\x02\x12\f\n" +
	"\bdatetime\x10\x03\x12\x10\n" +
	"\finteractions\x10\x042\xfa\x05\n" +
	"\rConversations\x12F\n" +
	"\x11CreateS2sPipeline\x12\x17.ondewo.csi.S2sPipeline\x1a\x16.google.protobuf.Empty\"\x00\x12F\n" +
	"\x0eGetS2sPipeline\x12\x19.ondewo.csi.S2sPipelineId\x1a\x17.ondewo.csi.S2sPipeline\"\x00\x12F\n" +
	"\x11UpdateS2sPipeline\x12\x17.ondewo.csi.S2sPipeline\x1a\x16.google.protobuf.Empty\"\x00\x12H\n" +
	"\x11DeleteS2sPipeline\x12\x19.ondewo.csi.S2sPipelineId\x1a\x16.google.protobuf.Empty\"\x00\x12_\n" +
	"\x10ListS2sPipelines\x12#.ondewo.csi.ListS2sPipelinesRequest\x1a$.ondewo.csi.ListS2sPipelinesResponse\"\x00\x12N\n" +
	"\tS2sStream\x12\x1c.ondewo.csi.S2sStreamRequest\x1a\x1d.ondewo.csi.S2sStreamResponse\"\x00(\x010\x01\x12X\n" +
	"\x13CheckUpstreamHealth\x12\x16.google.protobuf.Empty\x1a'.ondewo.csi.CheckUpstreamHealthResponse\"\x00\x12[\n" +
	"\x10GetControlStream\x12 .ondewo.csi.ControlStreamRequest\x1a!.ondewo.csi.ControlStreamResponse\"\x000\x01\x12_\n" +
	"\x10SetControlStatus\x12#.ondewo.csi.SetControlStatusRequest\x1a$.ondewo.csi.SetControlStatusResponse\"\x00b\x06proto3"

var (
	file_ondewo_csi_conversation_proto_rawDescOnce sync.Once
	file_ondewo_csi_conversation_proto_rawDescData []byte
)

func file_ondewo_csi_conversation_proto_rawDescGZIP() []byte {
	file_ondewo_csi_conversation_proto_rawDescOnce.Do(func() {
		file_ondewo_csi_conversation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ondewo_csi_conversation_proto_rawDesc), len(file_ondewo_csi_conversation_proto_rawDesc)))
	})
	return file_ondewo_csi_conversation_proto_rawDescData
}

var file_ondewo_csi_conversation_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_ondewo_csi_conversation_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_ondewo_csi_conversation_proto_goTypes = []any{
	(ControlStatus)(0),                      // 0: ondewo.csi.ControlStatus
	(ControlMessageServiceName)(0),          // 1: ondewo.csi.ControlMessageServiceName
	(ControlMessageServiceMethod)(0),        // 2: ondewo.csi.ControlMessageServiceMethod
	(ConditionType)(0),                      // 3: ondewo.csi.ConditionType
	(SipTrigger_SipTriggerType)(0),          // 4: ondewo.csi.SipTrigger.SipTriggerType
	(*S2SPipeline)(nil),                     // 5: ondewo.csi.S2sPipeline
	(*S2SPipelineId)(nil),                   // 6: ondewo.csi.S2sPipelineId
	(*ListS2SPipelinesRequest)(nil),         // 7: ondewo.csi.ListS2sPipelinesRequest
	(*ListS2SPipelinesResponse)(nil),        // 8: ondewo.csi.ListS2sPipelinesResponse
	(*S2SStreamRequest)(nil),                // 9: ondewo.csi.S2sStreamRequest
	(*S2SStreamResponse)(nil),               // 10: ondewo.csi.S2sStreamResponse
	(*SipTrigger)(nil),                      // 11: ondewo.csi.SipTrigger
	(*CheckUpstreamHealthResponse)(nil),     // 12: ondewo.csi.CheckUpstreamHealthResponse
	(*ControlStreamRequest)(nil),            // 13: ondewo.csi.ControlStreamRequest
	(*ControlStreamResponse)(nil),           // 14: ondewo.csi.ControlStreamResponse
	(*SetControlStatusRequest)(nil),         // 15: ondewo.csi.SetControlStatusRequest
	(*SetControlStatusResponse)(nil),        // 16: ondewo.csi.SetControlStatusResponse
	(*Condition)(nil),                       // 17: ondewo.csi.Condition
	(*ControlMessageServiceParameters)(nil), // 18: ondewo.csi.ControlMessageServiceParameters
	(*ControlMessage)(nil),                  // 19: ondewo.csi.ControlMessage
	(*nlu.DetectIntentResponse)(nil),        // 20: ondewo.nlu.DetectIntentResponse
	(*t2s.SynthesizeResponse)(nil),          // 21: ondewo.t2s.SynthesizeResponse
	(*structpb.Struct)(nil),                 // 22: google.protobuf.Struct
	(*status.Status)(nil),                   // 23: google.rpc.Status
	(*t2s.RequestConfig)(nil),               // 24: ondewo.t2s.RequestConfig
	(*s2t.TranscribeRequestConfig)(nil),     // 25: ondewo.s2t.TranscribeRequestConfig
	(*nlu.Context)(nil),                     // 26: ondewo.nlu.Context
	(*emptypb.Empty)(nil),                   // 27: google.protobuf.Empty
}
var file_ondewo_csi_conversation_proto_depIdxs = []int32{
	5,  // 0: ondewo.csi.ListS2sPipelinesResponse.pipelines:type_name -> ondewo.csi.S2sPipeline
	20, // 1: ondewo.csi.S2sStreamResponse.detect_intent_response:type_name -> ondewo.nlu.DetectIntentResponse
	21, // 2: ondewo.csi.S2sStreamResponse.synthesize_response:type_name -> ondewo.t2s.SynthesizeResponse
	11, // 3: ondewo.csi.S2sStreamResponse.sip_trigger:type_name -> ondewo.csi.SipTrigger
	4,  // 4: ondewo.csi.SipTrigger.type:type_name -> ondewo.csi.SipTrigger.SipTriggerType
	22, // 5: ondewo.csi.SipTrigger.content:type_name -> google.protobuf.Struct
	23, // 6: ondewo.csi.CheckUpstreamHealthResponse.s2t_status:type_name -> google.rpc.Status
	23, // 7: ondewo.csi.CheckUpstreamHealthResponse.nlu_status:type_name -> google.rpc.Status
	23, // 8: ondewo.csi.CheckUpstreamHealthResponse.t2s_status:type_name -> google.rpc.Status
	0,  // 9: ondewo.csi.ControlStreamResponse.control_status:type_name -> ondewo.csi.ControlStatus
	0,  // 10: ondewo.csi.SetControlStatusRequest.control_status:type_name -> ondewo.csi.ControlStatus
	0,  // 11: ondewo.csi.SetControlStatusResponse.old_control_status:type_name -> ondewo.csi.ControlStatus
	0,  // 12: ondewo.csi.SetControlStatusResponse.new_control_status:type_name -> ondewo.csi.ControlStatus
	3,  // 13: ondewo.csi.Condition.type:type_name -> ondewo.csi.ConditionType
	24, // 14: ondewo.csi.ControlMessageServiceParameters.t2s_config:type_name -> ondewo.t2s.RequestConfig
	25, // 15: ondewo.csi.ControlMessageServiceParameters.s2t_config:type_name -> ondewo.s2t.TranscribeRequestConfig
	26, // 16: ondewo.csi.ControlMessageServiceParameters.context:type_name -> ondewo.nlu.Context
	17, // 17: ondewo.csi.ControlMessageServiceParameters.condition_start:type_name -> ondewo.csi.Condition
	17, // 18: ondewo.csi.ControlMessageServiceParameters.condition_end:type_name -> ondewo.csi.Condition
	1,  // 19: ondewo.csi.ControlMessage.service:type_name -> ondewo.csi.ControlMessageServiceName
	2,  // 20: ondewo.csi.ControlMessage.method:type_name -> ondewo.csi.ControlMessageServiceMethod
	18, // 21: ondewo.csi.ControlMessage.parameters:type_name -> ondewo.csi.ControlMessageServiceParameters
	5,  // 22: ondewo.csi.Conversations.CreateS2sPipeline:input_type -> ondewo.csi.S2sPipeline
	6,  // 23: ondewo.csi.Conversations.GetS2sPipeline:input_type -> ondewo.csi.S2sPipelineId
	5,  // 24: ondewo.csi.Conversations.UpdateS2sPipeline:input_type -> ondewo.csi.S2sPipeline
	6,  // 25: ondewo.csi.Conversations.DeleteS2sPipeline:input_type -> ondewo.csi.S2sPipelineId
	7,  // 26: ondewo.csi.Conversations.ListS2sPipelines:input_type -> ondewo.csi.ListS2sPipelinesRequest
	9,  // 27: ondewo.csi.Conversations.S2sStream:input_type -> ondewo.csi.S2sStreamRequest
	27, // 28: ondewo.csi.Conversations.CheckUpstreamHealth:input_type -> google.protobuf.Empty
	13, // 29: ondewo.csi.Conversations.GetControlStream:input_type -> ondewo.csi.ControlStreamRequest
	15, // 30: ondewo.csi.Conversations.SetControlStatus:input_type -> ondewo.csi.SetControlStatusRequest
	27, // 31: ondewo.csi.Conversations.CreateS2sPipeline:output_type -> google.protobuf.Empty
	5,  // 32: ondewo.csi.Conversations.GetS2sPipeline:output_type -> ondewo.csi.S2sPipeline
	27, // 33: ondewo.csi.Conversations.UpdateS2sPipeline:output_type -> google.protobuf.Empty
	27, // 34: ondewo.csi.Conversations.DeleteS2sPipeline:output_type -> google.protobuf.Empty
	8,  // 35: ondewo.csi.Conversations.ListS2sPipelines:output_type -> ondewo.csi.ListS2sPipelinesResponse
	10, // 36: ondewo.csi.Conversations.S2sStream:output_type -> ondewo.csi.S2sStreamResponse
	12, // 37: ondewo.csi.Conversations.CheckUpstreamHealth:output_type -> ondewo.csi.CheckUpstreamHealthResponse
	14, // 38: ondewo.csi.Conversations.GetControlStream:output_type -> ondewo.csi.ControlStreamResponse
	16, // 39: ondewo.csi.Conversations.SetControlStatus:output_type -> ondewo.csi.SetControlStatusResponse
	31, // [31:40] is the sub-list for method output_type
	22, // [22:31] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_ondewo_csi_conversation_proto_init() }
func file_ondewo_csi_conversation_proto_init() {
	if File_ondewo_csi_conversation_proto != nil {
		return
	}
	file_ondewo_csi_conversation_proto_msgTypes[5].OneofWrappers = []any{
		(*S2SStreamResponse_DetectIntentResponse)(nil),
		(*S2SStreamResponse_SynthesizeResponse)(nil),
		(*S2SStreamResponse_SipTrigger)(nil),
	}
	file_ondewo_csi_conversation_proto_msgTypes[13].OneofWrappers = []any{
		(*ControlMessageServiceParameters_T2SConfig)(nil),
		(*ControlMessageServiceParameters_S2TConfig)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ondewo_csi_conversation_proto_rawDesc), len(file_ondewo_csi_conversation_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ondewo_csi_conversation_proto_goTypes,
		DependencyIndexes: file_ondewo_csi_conversation_proto_depIdxs,
		EnumInfos:         file_ondewo_csi_conversation_proto_enumTypes,
		MessageInfos:      file_ondewo_csi_conversation_proto_msgTypes,
	}.Build()
	File_ondewo_csi_conversation_proto = out.File
	file_ondewo_csi_conversation_proto_goTypes = nil
	file_ondewo_csi_conversation_proto_depIdxs = nil
}
